### ISSUE TITLE
When input and output datasets are re-used the job listing stacks the outputs and inputs

### ISSUE THREAD

**Issue by advanderveer** [nerdalize/nerd#355]
## Expected Behavior
```
JOB       IMAGE                       INPUT                                     OUTPUT                                        MEMORY   VCPU   CREATED AT      PHASE      DETAILS             
d3d-run   quay.io/nerdalize/delft3d   d3d-input   d3d-output   0.2      0.2    2 seconds ago   Starting   ContainerCreating 
```

## Actual Behavior
```
JOB       IMAGE                       INPUT                                     OUTPUT                                        MEMORY   VCPU   CREATED AT      PHASE      DETAILS             
d3d-run   quay.io/nerdalize/delft3d   d3d-input,d3d-input,d3d-input,d3d-input   d3d-output,d3d-output,d3d-output,d3d-output   0.2      0.2    2 seconds ago   Starting   ContainerCreating 
```

## Steps to Reproduce the Problem

  1. re-use one dataset in multiple jobs
  1. delete old jobs

**Comment by LilliJane** [comment]
This issue will need some design and thinking before we can solve it. 
Indeed, the problem here is that we map the datasets to the jobs when we list jobs. And if a job is run with a job name that was already used, when we run `nerd job list` we'll see an old dataset appear because it's referencing an old job which had the same name as the one running.

This can be seen as an issue or as a feature, depending on what the users want. Maybe some of them will want to compare the different inputs/outputs for a job and will want to keep track of what dataset was used for what job. At the same time, it is really confusing to start a job without input or output and see appear a multitude of datasets.

**Comment by borismattijssen** [comment]
I just ran into this and wanted to report it as a bug. So I personally wouldn't consider this a feature ;)
